const image = {
  logo: require('./work-insite-logo.webp'),
  sign_in: require('./siginin-illustration.webp'),
  user_start_img: require('./user-creation-illustration.webp'),
  contact_start_img: require('./contact-creation-illustration.webp'),
  client_creation: require('./client-creation-illustration.webp'),
  supplier_start_img: require('./supplier-creation-illustration.webp'),
  worker_start_img: require('./worker-creation-illustration.webp'),
  site_creation: require('./site-creation-illustration.webp'),
  aadhar_img: require('./Aadhaar.webp'),
  pan_img: require('./pan.webp'),
  gst_img: require('./gst.webp'),
  bank_account_img: require('./bank-account.webp'),
  google_pay_img: require('./google-pay.webp'),
  phonepe_img: require('./phonepe.webp'),
  upi_img: require('./upi.webp'),
  hsn_img: require('./hsn.webp'),
  bank_transfer_img: require('./bank-transfer.jpg'),
  bank_checks_img: require('./bank-checks.jpg'),
  cash_img: require('./cash-in-hand.png'),
  sign_up: require('./SignUp.jpg'),
   Verification_tick: require('./Vertification-tick.webp'),

};
export default image;
